sudo: required
addons:
  apt:
    packages:
    - docker-ce
services:
- docker
language: python
python:
- '3.3'
before_install:
- sudo /etc/init.d/mysql stop
- pwd
- ls -la
- sudo docker-compose up -d
- docker --version
- pip install selenium
script:
- echo "Waiting a bit before pinging the containers..."
- sleep 15
- curl localhost:8080
- curl localhost:4444
- curl localhost:8081
- echo "Starting tests..."
- python 2test.py
- if [ $(grep -nr '<<<<<<' . | wc -l) -gt 1 ]; then exit 1; fi
before_deploy:
- tar -cvf src.tar files/*
deploy:
  provider: releases
  api_key:
    secure: waS8hP4LT1R0R+dMiCBEov2CUQgH04ZrzRz0Zq5xuaeKNSsK9/HiLZtYawZ06cidPO97cZcmTqO3FZ9ha5CkdFsCiUAN95FN4lu4/sN2JkJM3X1Ov1gqdKVzZ7aXX01CNQiQf/SbU8bi+NCYerFT+7DucpWHIVhSnEDq3ejVahUgV4OS0Nv7M5fbRdtw321PXEYZ1SgRAMf6PJ8mVhIjWI/fJpA1Tl73yPmP2Z93deKdPuODf+wvTyrOvVsFHE1pTq9K5J2rHKaDkejLBMwwuXqbZnVKAllQHbiakSITWftf4T3eNetwL4Dyk3ZRNmxwvdbjke1xdqL/XesR5lODu55Z9bG//e7Pjb/DF4JvvSwYYS+2HYOebr6Mo2lTrkJSEkGlCbIn2cgOfuBoUrIIEhm3iF7hE21mg5d7d1XRWAOXFHs1NM8UkATRxTMXdiuSspz25tzjUmfoCANCxYIIBjlRciT3kVh05VKEwO/HvFmrwcIsDmUumYubhoizUjekTD6LRYC/cTnQAcYvd82swBn2moFbr9Ya82qzAOqlqSCxHiEAL1FPUFq7dwMqPUHkipu8O9DiYgo+7CWcPZGOddbZ9XziYjDxdcfZFp+nd03ywMfQpQrDCakj1dg8drAQPogFy4uIc6cLZ28Pjvc8u9n6hgAVr50II4QnkiL1o0A=
  file: src.tar
  skip_cleanup: true
  on:
    repo: echoffee/travis-test
    tags: true
