
sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
        - docker

language: python
python:
        - "3.3"
before_install:
        - sudo /etc/init.d/mysql stop
        - pwd
        - ls -la
        - sudo docker-compose up -d
        - docker --version
        - pip install selenium

script :
                - echo "Waiting a bit before pinging the containers..."
                - sleep 15
                - curl localhost:8080
                - curl localhost:4444
                - curl localhost:8081
                - echo "Starting tests..."
                - python 2test.py
