sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
        - docker

language: python
python:
        - "3.3"
before_install:
        - sudo /etc/init.d/mysql stop
        - pwd
        - ls -la
        - sudo docker-compose up -d
        - docker --version
        - pip install selenium
script:
        - curl localhost:8080
        - curl localhost:4444
        - python 2test.py
