sudo: required

services:
        - docker

language: python
python:
        - "3.3"
before_install:
        - sudo /etc/init.d/mysql stop
        - pwd
        - ls -la
        - docker-compose up -d
        - pip install selenium
script:
        - python 2test.py
